Feature/product 리뷰 반영 및 문제 해결 중
ingdaeho/node-DMfriends pull request #3
Opened 2021-02-02 04:49 UTC by ingdaeho

2021-02-03 10:47 UTC, Jun4928 requested changes

2021-02-03 10:47 UTC, Jun4928 commented on controllers/FeedController.js
> +      id: foundStatusId,
여기도 반복되는 코드를 줄이려면 어떻게 해야하는지 고민 해 보세요.
feature/cart 에 달아드린 리뷰를 참고하시면 됩니다

2021-02-03 10:47 UTC, Jun4928 commented on services/ProductService.js
> +  await prisma.$transaction([getDetailInfo, addToRecentViews]);
GOOD

2021-02-03 11:08 UTC, ingdaeho commented on services/ProductService.js
> +                      equals: "thumbnail",
예를 들어 product_id: 2인 제품의 상세정보를 불러오면, recent_view에서도 product_id: 2인 recent_view 만 불러와지더라구요..
위 코드의 where와 상관없이 다른 product_id를 가진 상품들이 불러와지지가 않는데 모델링 문제일까요?

2021-02-04 05:48 UTC, Jun4928 commented on services/ProductService.js
> +                      equals: "thumbnail",
recent_views 를 조회 할 때, 
**해당 유저**가 본 상품을 가져와야 하니까
recent_views 를 쿼리하는 where 절에 user_id 가 필요하지 않을까요? 
일단 
```js
product_id: { 
  not: value
}
```
옵션은 지우고, user_id 로 조회해서 해당 유저가 본 모든 상품을 모두 다 가져오는지 확인 해 보세요

2021-02-09 01:20 UTC, Jun4928 reviewed
대호님! 엔드포인트 분리하니까 로직 훨씬 깔끔하고 좋네요!

2021-02-09 01:20 UTC, Jun4928 commented on services/ProductService.js
> +  });
👍👍

2021-02-16 06:03 UTC, merged