Add: 장바구니 기능 추가
ingdaeho/node-DMfriends pull request #4
Opened 2021-02-02 06:15 UTC by ingdaeho

2021-02-03 10:45 UTC, Jun4928 requested changes
리뷰 확인 해 주세요 👍 
대호님 잘 하고 계십니다 👍 👍

2021-02-03 10:45 UTC, Jun4928 commented on services/CartService.js
> +    take: Number(limit) || ARTICLES_DEFAULT_LIMIT,
설령 articles 엔티티의 기본 오프셋, 리밋 값이 같다고 해도, 변수명은 다르게 해 주세요

2021-02-03 10:45 UTC, Jun4928 commented on services/CartService.js
> +    where: { id: cartId || 1 },
upsert 를 사용하신 것은 좋지만,
- cartId 가 없는 경우에 무조건 1번이 default가 되는 것 인가요?

2021-02-03 10:45 UTC, Jun4928 commented on services/CartService.js
> +      id,
이미 고유한 cart 의 id가 넘어오고 있습니다.  
- where 절에 product_id가 필요할까요?
- unique 한 id 로 조회를 하고 있습니다. updateMany 가 의미가 있을까요?

2021-02-03 10:45 UTC, Jun4928 commented on services/CartService.js
> +    data: {
이 경우에는 user의 모든 카트를 비우고 있기 때문에 updateMany를 잘 사용 하셨습니다 👍

2021-02-03 10:45 UTC, Jun4928 commented on controllers/CartController.js
> +  });
해당 유저와 제품이 카트에 담겨있는지 확인하는 코드 굳!

2021-02-03 10:45 UTC, Jun4928 commented on controllers/CartController.js
> +  }
## 반복되는 코드 줄이기 
이렇게 반복되는 코드를 어떻게 줄일 수 있을까요?
지난 번 세션 때 이야기 했던 것 처럼 **중복** 되는 것이 무엇인지 먼저 파악 해야 합니다.
1. CartService.addItem 함수를 세 조건 모두 호출하고 있습니다.
2. 결과를 itemAdded 라는 변수에 담아서 json 메소드로 응답을 보내고 있습니다. 

그럼 조건마다 **달라지는 것**은 무엇일까요? 
CartService.addItem 함수에 들어가는 인자인 **객체** 입니다.
객체도 지금 네가지 필드가 모두 중복되고 있고, cartId 만 조건에 따라 있거나 없거나 하고 있네요.

### 객체 만들기 
```js
const addItemInput = {
  user_id: userIdFromToken,
  product_id,
  quantity,
  price,
  cartId: foundCart?.product_id === product_id && foundCart.id 
} 
```

1. optional chaining 으로 foundCart 의 존재유무를 체크할 수 있습니다. 없다면 false 가 cartId에 담깁니다.
2. foundCart가 존재하고 product_id 가 같다면 카트의 아이디를 담아 줍니다.
3. 같지 않다면 false 를 담습니다. 

### 서비스 로직 태우기 
이렇게 만들어진 객체를 서비스 로직의 인자로 넣어주면 되겠죠
```js
const itemAdded = await CartSerivce.addItem(addItemInput)
res.status(201).json({ itemAdded })
```

2021-02-03 11:26 UTC, ingdaeho commented on services/CartService.js
> +      id,
어떤 product_id가 없다는 것은 어떤 product를 삭제할지 정해주지 않는다고 생각하여서 product_id를 넘겨주었습니다.
cart 안에 여러 product_id가 있기 때문에 updateMany를 사용해서 user가 cart에 담고 있는 모든 제품을 불러와야되는거 아닌가요?

2021-02-04 02:09 UTC, ingdaeho commented on controllers/CartController.js
> +  }
와우 너무 간단 명료하게 줄여지네요

2021-02-04 02:12 UTC, ingdaeho commented on controllers/CartController.js
> +  });
foundCart 함수가 여러곳에서 계속 중복되어 쓰이고 있는데 이것도 줄일 수 있는 방법이 있을까요? 따로 빼는게 좋을까요?

2021-02-04 02:28 UTC, ingdaeho commented on services/CartService.js
> +    where: { id: cartId || 1 },
1번으로 해두면 db에서 1이 이미 사용되었던걸 인식해서인지 자동으로 마지막 id값 이어서 추가되어서 임시로 1로 해둔건데 
다른 좋은 방법이 있을까요..

2021-02-04 05:56 UTC, Jun4928 commented on services/CartService.js
> +      id,
updateMany를 사용하신 이유가 선택된 product_id를 삭제 하고 난 후의 장바구니에 담긴 모든 제품을 불러오려고 하신 것 같네요.

함수의 역할은 단순하면 단순 할 수록 좋습니다.
선택된 아이템 **하나**를 삭제하고 있습니다. 
update 로 고유한 cartId 로 조회해서 delete_at 을 업데이트 시켜주고,
업데이트 된 카트의 상태를 response 로 반환하고 싶다면 이미 구현된 getItems 를 사용해 주세요

2021-02-04 05:59 UTC, Jun4928 commented on services/CartService.js
> +    where: { id: cartId || 1 },
upsert 는 해당 where 절을 통해서 있으면 업데이트를 하고, 없으면 row 를 create 하는 함수 입니다. 
cartId가 없다면 항상 cartId가 1번인 아이템을 업데이트 하지 않을까요?

2021-02-04 07:24 UTC, ingdaeho commented on services/CartService.js
> +    where: { id: cartId || 1 },
cartId를 1번으로 해놓아도 cartId가 없을경우 자동으로 마지막 cartId를 이어서 새로 생성되더라구요
cartId를 1로 해놓는게 결코 좋은 방법은 아니라고 저도 생각하는데 다른 방법이 마땅히 떠오르지 않았습니다..

2021-02-09 01:25 UTC, Jun4928 commented on services/CartService.js
> +  });
**create**, **update** 두 메소드 모두 생성, 업데이트 한 데이터를 객체로 리턴합니다. 
객체를 리턴 해 주고 싶다면 다시 DB에서 조회(findFirst)해서 return 하는 것이 아니라 
다음과 같이 Promise를 리턴하는 메소드 자체를 리턴 해 주면, 컨트롤러에서 받아서 사용할 수 있습니다. 
```js
if (!foundCart) return prisma.cart.create({...})

return prisma.cart.update({...}
```

2021-02-09 04:14 UTC, ingdaeho commented on services/CartService.js
> +  });
준님 수정했습니다! 
나머지 작업하고 있는거 다하면 말씀드리려했는데 알림이 갔나보군요

2021-02-09 04:23 UTC, ingdaeho commented on services/CartService.js
>  };
user_id로 조회해서 cart안에 user와 연관되어있는 product_id를 다 불러와서 
req로 받은 product_id를 비교해서 deleted_at을 업데이트 시켜주려고 updateMany를 사용했는데,
여기서 만약 상품을 하나만 받을때는 
``
{
  product_id: 2
}
``
이런식으로 받으면 삭제가 가능한데,
``
[
  {
    product_id: 2
  },
  {
    product_id: 3
  }
]
``
이렇게 배열에 여러 product_id를 받으면 어떻게 해야할지 잘 모르겠습니다.. 애초에 저렇게 받는게 맞는걸까요?

2021-02-16 04:24 UTC, Jun4928 commented on services/CartService.js
>  };
updateMany 를 사용하지 않고 고유한 ID를 찾아서 업데이트 시키는 update 메소드를 사용해야 합니다.

다음과 같이 서비스 로직에서 transaction 을 사용하면 되겠네요
ex)
```js
const selectedItems = [{ product_id: 2 }, { product_id: 3 }] // 항상 이렇게 배열 형태로 받는것이 좋습니다.
const deleteItems = selectedItems.map(({ product_id }) => 
  prisma.update(
    { where: { user_id, product_id }, data: { deleted_at: new Date() } }
  )) 
// product_id 를 바로 구조분해 할당하고, 모든 배열의 요소에 대해서 update 함수를 실행시켜서 Promise 를 객체를 담습니다.

await prisma.$transaction(deleteItems) // 
```

2021-02-16 06:00 UTC, merged